const {
  VITE_GG_YOUTUBE_KEY: GG_YOUTUBE_KEY,
  VITE_GG_YOUTUBE_BASE_URL,
  VITE_YOUTUBE_MP3_KEY: YOUTUBE_MP3_KEY,
  VITE_YOUTUBE_MP3_BASE_URL,
  VITE_YOUTUBE_MP3_HOST,
  VITE_YOUTUBE_QUERY_KEY: YOUTUBE_QUERY_KEY,
  VITE_YOUTUBE_QUERY_BASE_URL,
  VITE_YOUTUBE_QUERY_HOST,
  VITE_YOUTUBE_CUSTOM_BASE_URL,
} = import.meta.env;

const BASE_URL = {
  youtubeGGQuery: VITE_GG_YOUTUBE_BASE_URL,
  youtubeQuery: VITE_YOUTUBE_QUERY_BASE_URL,
  youtubeToMP3: VITE_YOUTUBE_MP3_BASE_URL,
  youtubeCustom: VITE_YOUTUBE_CUSTOM_BASE_URL,
};

const HOST_URL = {
  youtubeToMP3: VITE_YOUTUBE_MP3_HOST,
  youtubeQuery: VITE_YOUTUBE_QUERY_HOST,
};

const RAPID_HEADER = {
  rapidKey: 'x-rapidapi-key',
  rapidHost: 'x-rapidapi-host',
};

const AXIOS_TIMEOUT = 5000;

export {
  RAPID_HEADER,
  HOST_URL,
  BASE_URL,
  GG_YOUTUBE_KEY,
  YOUTUBE_MP3_KEY,
  YOUTUBE_QUERY_KEY,
  AXIOS_TIMEOUT,
};
