# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    name: my-job
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        bun-version: [1.2.7]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        # uses: actions/setup-node@v4
        uses: oven-sh/setup-bun@v2 # using bun instead of node: readmore (https://bun.sh/guides/runtime/cicd)
        with:
          # node-version: ${{ matrix.node-version }}
          bun-version: ${{matrix.bun-version}}
          cache: 'bun'
      # - run: npm ci
      # - run: npm run build --if-present
      # - run: npm test
      - run: bun install --frozen-lockfile
      - run: bun run lint
      - run: bun run build --node
      - run:  |
          echo "The job_id is: $GITHUB_JOB"   # reference the default environment variables
          echo "The id of this action is: $GITHUB_ACTION"   # reference the default environment variables
          echo "The run id is: $GITHUB_RUN_ID"
          echo "The GitHub Actor's username is: $GITHUB_ACTOR"
          echo "GitHub SHA: $GITHUB_SHA"
